### ISSUE TITLE
html characters &lt; instead <  in "Notes"    

### ISSUE THREAD

**Issue by salvadorrueda** [JovianML/jovian-py#187]
Editing "Notes" when I was comparing different Notebook's version and I tried to add a Note like 
"test_acc <-> test_loss"

it saves 
test_acc &amp;lt;-&amp;gt; test_loss 

instead.

**Comment by sidujjain** [comment]
Thanks for reporting @salvadorrueda! We will fix it soon

**Comment by sidujjain** [comment]
@salvadorrueda this has been fixed
