### ISSUE TITLE
LaTeX Codes are not Rendered when Switching Tabs

### ISSUE THREAD

**Issue by ZenithClown** [JovianML/jovian-py#209]
Created a First Notebook with some LaTeX Equations (both using `$` markdown syntax and `\begin{equation}...\end{equation}` syntax), and the file is rendered properly at first:
![image](https://user-images.githubusercontent.com/16843145/93686757-1a55d700-fad6-11ea-8828-7c584fe2e9e7.png)

But once switching tabs, then the same is not rendered:
![image](https://user-images.githubusercontent.com/16843145/93686780-45d8c180-fad6-11ea-949a-f65cce99eff0.png)

## Steps to Reproduce
1. Created a New Notebook in Local Machine (using Linux, configuration as below)
![image](https://user-images.githubusercontent.com/16843145/93686818-8d5f4d80-fad6-11ea-902e-943e83b70bfe.png)

2. Uploaded notebook using jovian:
```python
# Uploading to https://jovian.ml/dpramanik
import jovian
jovian.commit(files = ["autograd.py"])
```

3. Switched to Tab: `Files`
4. Returned to Tab: `Notebook`

[Notebook URL](https://jovian.ml/dpramanik/pytorch-1-basic-data-types-and-gradient-calculations)

**Comment by ZenithClown** [comment]
I would also like to add, I have tried to refresh the page, and check again - but the same problem. I am using Chrome:
![image](https://user-images.githubusercontent.com/16843145/93686928-327a2600-fad7-11ea-8097-748bb59bdf3b.png)

**Comment by sonakshs** [comment]
Thanks for reporting the bug @ZenithClown, we'll have a fix ready very soon.

**Comment by sidujjain** [comment]
Hi @ZenithClown, thanks for reporting the issue! We were able to track down the Mathjax rendering issue and it has been fixed. Please give it a try again and let us know if you see any other issues.

**Comment by ZenithClown** [comment]
Looks fine 👍
